### ISSUE TITLE
the build is failing so i have pull the changes directly to the demo.

### ISSUE THREAD

**Issue by ankitjain28may** [dbjpanda/affiliates_connect_demo#14]

**Comment by dbjpanda** [comment]
Build failing because my travs is unable to decrypt the ssh key encrypted by you. Let me add the key.

**Comment by ankitjain28may** [comment]
Yes, that's the reason for the failing of build for your repo but it was failing at my repo too because the mysql_username is set to 'test' in a .env.example file as well as the hash_salt is not set which I have fixed in the PR #15

**Comment by dbjpanda** [comment]
I overwrote the deploy_key for the repo. Please add below public key to your ssh authorised file in server. 

`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3nfATaagtJBnFaj8Yd8cjMgoULLN9hoeG8Nh5FnC/I1coOIs6l02AvVToUSkCs9/iJFVWIQg9kZdzm5VwiUyzmPi8YqcQXWxzTngzR+NBMNGXwjKPoQDPZFy8mHQENTeYLQlv7x03naxO9km9RYkwsfbv8cNsszelRmDlJU3iepnu8BNPwkehEAkZ5IkzBgAYZr0q33FIN06e2juhaP/97W5H4UPWukygevy68zPdW6jNoav7CAfsC1WODdqxx0Jwl0lE5JEveN+Q8k4RTC+2Trd2BoN81Uq8qdJGjjzeTWpA3wcq6CEhDCJDm8VsWuCfNpgTqdM8yt4AD6LTn0I9 dibya.dev94@gmail.com
`

**Comment by ankitjain28may** [comment]
@dbjpanda I have added above-given key.
