### ISSUE TITLE
Pull Traefik image first.

### ISSUE THREAD

**Issue by ParitoshikPaul** [dbjpanda/affiliates_connect_demo#2]
Unable to find image 'traefik:latest' locally
latest: Pulling from library/traefik
03732cc4924a: Pull complete 
0a29083ad5e1: Pull complete 
Digest: sha256:98d82a5fa9a27382de1666ecd385d32fdaa89266a8426b378b040c68c345bf85
Status: Downloaded newer image for traefik:latest
323bcf20837b5d18a60fd88433c38d17ec93e010c3808dbc4bd0b738c59595d6
docker: Error response from daemon: driver failed programming external connectivity on endpoint traefik (29cc846ca7bf8ec18412f7eda24ec0b58b9b68112b8804dc8c057b151c8a0aec): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE).

**Comment by dbjpanda** [comment]
"docker run" automatically pulls the image if not exist. Still I have fixed that. Though its an extra command. :)
